# Generated by Django 2.2.3 on 2020-10-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_person_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
